development:
  adapter: mysql2
  database: vida_development
  username: root
  password: huxia001
  host: 192.168.10.7
  encoding: utf8

production:
  adapter: mysql2
  database: vida_development
  username: root
  password: huxia001
  host: 192.168.10.7
  encoding: utf8
  prepared_statements: false

test:
  adapter: mysql2
  database: vida_test
  username: root
  password: huxia001
  host: localhost
  encoding: utf8
